---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - prometheus_configure
        - prometheus_install
        - prometheus_run
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - prometheus_install
  tags:
    - prometheus_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - prometheus_configure
  tags:
    - prometheus_configure

- name: Ensure prometheus service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: "{{prometheus_service_state}}"
    enabled: "{{prometheus_service_enabled}}"
  tags:
    - prometheus_run
